#
# This file contains a url check with a bad URL.


ok_label: bad configuration
sysinfo_command: top

checks:

  bad_url:
    url: foo
    bad_key: 1

  bad_df:
    limit: 150
    lower: abc
    limit_/var: def
    lower_/var: 160
    bad_key: 1

  bad_sys:
    load_limit: abc
    mem_limit: abc
    swap_limit: abc
    procs_limit: abc
    load_lower: abc
    mem_lower: abc
    swap_lower: abc
    procs_lower: abc
    load_critical: abc
    mem_critical: abc
    swap_critical: abc
    procs_critical: abc
    bad_key: 1
